POST HTTP://localhost:5050/products/create HTTP/1.1s
Content-Type: application/json

{
    "nameProduct": "iphon",
    "description": "il piu bello del mondo",
    "price": 450,
    "category":"65423fc8ce8e84dfc11748ca",
    "image": "https://www.telefonino.net/app/uploads/2021/09/iPhone-13-sfondo.jpg",
    "scount": "sconto"
}

####
PATCH  HTTP://localhost:5050/products/update/65441329efbdba3404b8750c HTTP/1.1s
Content-Type: application/json
    
{
    "nameProduct": "franco",
    "description": "ole",
    "price": 98
    
}

####
GET HTTP://localhost:5050/products HTTP/1.1s
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1NDI4OWIxMTI4YjYxOTBlZTIwYTU2NSIsIm5hbWUiOiJwYW9sbyIsImxhc3RuYW1lIjoicGVsbGVncmlubyIsImVtYWlsIjoicEBnbWFpbC5jb20iLCJzb2NpdHkiOiJyb3Nzb3JlZSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTY5ODg1OTQ5OSwiZXhwIjoxNjk5MTE4Njk5fQ.Y4dVEIPe_T3Bnp1WAsHo5obg-9fS-ViTgBrUg_85wh0
####
DELETE HTTP://localhost:5050/products/delete/6539037e0c38f396e4631daa

####
GET HTTP://localhost:5050/products/category/65423fc8ce8e84dfc11748ca HTTP/1.1s
Content-Type: application/json

####
POST HTTP://localhost:5050/providers/create HTTP/1.1s
Content-Type: application/json

{
    "name": "paolo",
    "lastname": "pellegrino",
    "email": "p@gmail.com",
    "password": "ciao99",
    "socity": "rossoree",
    "role": "admin"

}

####
POST HTTP://localhost:5050/category/create HTTP/1.1s
Content-Type: application/json

{
    "category": "cellulari"
    
}
####

POST HTTP://localhost:5050/client/create HTTP/1.1s
Content-Type: application/json

{
    "name": "paolo",
    "lastname": "pellegrino",
    "email": "p.pellegrino@gmail.com",
    "password": "ciao99",
    "role": "user"

}

####
POST HTTP://localhost:5050/basket/create HTTP/1.1s
Content-Type: application/json

{
    "userId": "653a8af1f5823b77a3206c83",
    "productId": "653a899981bbcbe56e716fe8"
    }
   


####
GET  HTTP://localhost:5050/basket HTTP/1.1s

####

POST HTTP://localhost:5050/loginprovider HTTP/1.1s
Content-Type: application/json

{
    "email": "p@gmail.com",
    "password": "ciao99"
    }

####
POST HTTP://localhost:5050/loginclient HTTP/1.1s
Content-Type: application/json

{
    "email": "p.pellegrino@gmail.com",
    "password": "ciao99"
    }

####
POST HTTP://localhost:5050/verifycode HTTP/1.1s
Content-Type: application/json

{
    "secretCode": "9c98d48916c2e7119906596c0f2cfae0a947354b41b8eac0b802831c0b00a288"
}

####
GET  HTTP://localhost:5050/products/65423fc8ce8e84dfc11748ca HTTP/1.1s
Content-Type: application/json